"""
Pydantic schemas package.
"""

from .base import (
    BaseSchema,
    TimestampMixin,
    SuccessResponse,
    ErrorResponse,
    PaginatedResponse,
    DataResponse,
    ListResponse,
    DeleteResponse,
    PaginationParams,
    SearchParams,
    DateRangeParams,
)

from .auth import (
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    ChangePasswordRequest,
    UserInfo,
    LoginResponse,
    LogoutResponse,
)

from .user import (
    RoleBase,
    RoleCreate,
    RoleUpdate,
    RoleResponse,
    RoleListResponse,
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
    UserBlockRequest,
    UserPasswordReset,
)

from .product import (
    UOMBase,
    UOMCreate,
    UOMUpdate,
    UOMResponse,
    UOMListResponse,
    CategoryBase,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    CategoryTreeResponse,
    CategoryListResponse,
    ProductUOMConversionBase,
    ProductUOMConversionCreate,
    ProductUOMConversionResponse,
    UniversalUOMConversionCreate,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    ProductResponse,
    ProductListItem,
    ProductListResponse,
    ProductSearchParams,
    ProductStockInfo,
    BulkPriceUpdateRequest,
)

from .customer import (
    CustomerBase,
    CustomerCreate,
    CustomerUpdate,
    CustomerResponse,
    CustomerListItem,
    CustomerListResponse,
    CustomerSearchParams,
    CustomerDebtResponse,
    CustomerDebtListResponse,
    CustomerPaymentRequest,
    CustomerAdvanceRequest,
    VIPLoginRequest,
    VIPCustomerResponse,
    VIPCredentialsCreate,
)

from .sale import (
    SaleItemCreate,
    SaleItemResponse,
    PaymentCreate,
    PaymentResponse,
    SaleCreate,
    SaleResponse,
    SaleListItem,
    SaleListResponse,
    SaleSearchParams,
    SaleCancelRequest,
    QuickSaleRequest,
    SaleReceiptResponse,
    SaleReturnItemCreate,
    SaleReturnCreate,
    SaleReturnResponse,
)

from .warehouse import (
    WarehouseBase,
    WarehouseCreate,
    WarehouseUpdate,
    WarehouseResponse,
    WarehouseListResponse,
    StockResponse,
    StockListResponse,
    StockSearchParams,
    StockMovementCreate,
    StockMovementResponse,
    StockMovementListResponse,
    StockMovementSearchParams,
    StockIncomeItemCreate,
    StockIncomeCreate,
    InventoryCheckItemCreate,
    InventoryCheckCreate,
    InventoryCheckItemResponse,
    InventoryCheckResponse,
    InventoryCheckUpdateItem,
    InventoryCheckComplete,
    StockTransferItemCreate,
    StockTransferCreate,
    StockTransferResponse,
    StockTransferReceive,
)
